### ISSUE TITLE
migration_core is not working in TYPO3 8.7.15

### ISSUE THREAD

**Issue by Moongazer** [franzholz/migration_core#1]
I want to try tt_products in TYPO3 8.7.15 but receiving this error:

> PHP Fatal error: Interface 't3lib_Singleton' not found in D:\\Workspace\\htdocs\\...\\ext\\tt_products\\pi1\\class.tx_ttproducts_pi1.php on line 47

For test purposes, I edited the class file from `class tx_ttproducts_pi1 implements t3lib_Singleton` to
`class tx_ttproducts_pi1 implements \TYPO3\CMS\Core\SingletonInterface`. This solves the error for this file and it runs into the same error in the next loaded class.

So it seems that the extension **migration_core** is not working, but I see it loaded in the Extension Manager. If I place an invalid PHP statement inside the `ClassAliasMapResult.php` file, no error is thrown which for me means that this file is never loaded by TYPO3 to return the ClassAliasMap array.

**Comment by franzholz** [comment]
The extension migration_core works without any problems.You must clean your composer cache.

see https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Autoloading/Index.html

The file `ClassAliasMapResult.php` must be detected and loaded by the TYPO3 autoloader.

**Comment by Moongazer** [comment]
Thank you very much for this hint! I didn't use composer and installed the extension manually by ZIP, thats why.

So manualy dumping the autoloader file through the Install-Tool ("Dump Autoload Information") solved the issue.
