### ISSUE TITLE
Installation via composer not possible

### ISSUE THREAD

**Issue by typecat** [franzholz/migration_core#2]
`composer require jambagecom/migration-core ^0.1` throws following error:
> The requested package jambagecom/migration-core could not be found in any version, there may be a typo in the package name.

I'm trying to install it for TYPO3 8.7 and according to the readme I have to require a version 0.1.x.
The repositories section of my composer.json looks like this:
```
"repositories": {
        "typo3": {
            "type": "composer",
            "url": "https://composer.typo3.org/"
        },
...
},
"minimum-stability": "dev",
...
```
Am I missing something? Is it a different repository? I already checked https://packagist.org/, but didn't find it.

**Comment by franzholz** [comment]
From where is the package "jambagecom/migration-core" requested?

This package should be requested instead: "typo3-ter/migration-core"

**Comment by typecat** [comment]
I requested it like this, because that's the name defined in your composer.json. Just like I request EXT:news by `compoer require georgringer/news ^6.1` (see https://github.com/georgringer/news/blob/master/composer.json)

**Comment by typecat** [comment]
FYI: I found this repo via TER https://extensions.typo3.org/extension/migration_core/ the composer.json there also defines `"name": "jambagecom/migration-core",`.

**Comment by franzholz** [comment]
Is the registration at "https://packagist.org" needed for composer?
Do you still have an error message?

**Comment by typecat** [comment]
As far as I know - not. The error message is in the description.
I'm not a composer expert, but based on my experience the name defined in the composer.json should be the name you use in the composer require statement.
Furthermore, I don not know, how package registration for composer.typo3.org works, but maybe you check it there ;)

**Comment by franzholz** [comment]
I do not know which "composer require" you mean. 
The extension migration_core uses no such "composer_require".
I am just following the example recommendations from 
https://composer.typo3.org/
and
https://github.com/helhum/ext_scaffold/blob/master/composer.json

**Comment by typecat** [comment]
As it is not recommended to manually edit the composer.json of the project, the way to add new extension is to use the "composer require" statement on cli (e.g. `compoer require georgringer/news ^6.1` ). The extension requirement will be automatically inserted into the requirements section of the project's  composer.json.
I have really no clue, how publishing extensions on TER works. According to https://composer.typo3.org/ your composer.json seems right though.

Have you tried installing your extension via composer yourself?

**Comment by franzholz** [comment]
I did never use composer so far manually, because I already have the TYPO3 website installed. AFAIK the TYPO3 Extension Manager uses composer by itself. I have no idea how it works to use the command line composer with an already present TYPO3 website which has not been installed using composer.
Maybe composer does not find the domain "jambagecom". But it should know about the domain "typo3-ter". The extension installs well with the Extension Manager. And its file composer.json is correct. TYPO3 only knows the `typo3-ter` namespace. You should not use the news extension as a reference.

Try it out this way:
`composer require typo3-ter/migration-core ^0.1`

**Comment by typecat** [comment]
This is the vendor name, not the domain. I've tried it yesterday and it works.
The news extension was just an example, I could name you much more which I can find on TER and install them via composer using the name defined in the composer.json.
Could you add this to the documentation? I can imagine, other people who switch to composer mode could run into the same problem.

**Comment by franzholz** [comment]
I have added now a better documentation into the README.md file at

https://github.com/franzholz/migration_core

**Comment by typecat** [comment]
Thanks. ;) Just took a look with my colleague on this:

The registration at "https://packagist.org" is not a must, but strongy recommended. You need to register your extension name (jambagecom/migration-core) there, so it can be installed via composer like I tried.
